spring:
  application:
    name: spring-boot-learn
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://192.168.231.140:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    type: com.zaxxer.hikari.HikariDataSource

